export const MySkillsQuery = [
  {
    image: "/images/skills/html.png",
    name: "HTML",
    time: "5 years",
    tags: ["Frontend", "Mobile"],
  },
  {
    image: "/images/skills/css.png",
    name: "CSS",
    time: "5 years",
    tags: ["Frontend", "Mobile"],
  },
  {
    image: "/images/skills/js.png",
    name: "JavaScript",
    time: "5 years",
    tags: ["Frontend", "Mobile"],
  },
  {
    image: "/images/skills/git.png",
    name: "Git",
    time: "5 years",
    tags: ["Others"],
  },
  {
    image: "/images/skills/react.png",
    name: "React",
    time: "4 years",
    tags: ["Frontend", "Mobile"],
  },
  {
    image: "/images/skills/mssql.png",
    name: "Microsoft SQL Server",
    time: "4 years",
    tags: ["Database"],
  },
  {
    image: "/images/skills/typescript.png",
    name: "TypeScript",
    time: "4 years",
    tags: ["Frontend", "Mobile"],
  },
  {
    image: "/images/skills/python.png",
    name: "Python",
    time: "3 year",
    tags: ["Backend"],
  },
  {
    image: "/images/skills/c.png",
    name: "C",
    time: "3 years",
    tags: ["Backend"],
  },
  {
    image: "/images/skills/vue.png",
    name: "Vue",
    time: "3 years",
    tags: ["Frontend", "Mobile"],
  },
  {
    image: "/images/skills/nextjs.png",
    name: "Next.js",
    time: "3 years",
    tags: ["Frontend", "Mobile"],
  },
  {
    image: "/images/skills/tailwindcss.png",
    name: "Tailwind CSS",
    time: "3 years",
    tags: ["Frontend", "Mobile"],
  },
  {
    image: "/images/skills/nodejs.png",
    name: "Node.js",
    time: "3 years",
    tags: ["Backend"],
  },
  {
    image: "/images/skills/java.png",
    name: "Java",
    time: "2 years",
    tags: ["Backend"],
  },
  {
    image: "/images/skills/graphql.png",
    name: "GraphQL",
    time: "2 years",
    tags: ["Frontend", "Mobile"],
  },
  {
    image: "/images/skills/nestjs.svg",
    name: "NestJS",
    time: "2 years",
    tags: ["Backend"],
  },
  {
    image: "/images/skills/flutter.png",
    name: "Flutter",
    time: "1 year",
    tags: ["Frontend", "Mobile"],
  },
  {
    image: "/images/skills/mongodb.png",
    name: "MongoDB",
    time: "1 year",
    tags: ["Database"],
  },
  {
    image: "/images/skills/materialui.jpg",
    name: "Material UI",
    time: "1 year",
    tags: ["Frontend", "Mobile"],
  },
  {
    image: "/images/skills/gcp.webp",
    name: "Google Cloud Platform",
    time: "1 year",
    tags: ["Cloud"],
  },
  {
    image: "/images/skills/socketio.png",
    name: "Socket.IO",
    time: "1 year",
    tags: ["Backend", "Frontend"],
  }
];
